Ottostugan/Controllers/MainController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ottostugan.DAL;
using Ottostugan.Models;
using Ottostugan.ViewModels.Main;

namespace Ottostugan.Controllers
{
    public class MainController : Controller
    {
        //
        // GET: /Main/

        public ActionResult Footer()
        {

            IList<Preference> preferences;

            using (var db = new OttostuganContext())
            {
                preferences = db.Preferences.ToArray();
            }

            var model = new FooterModel();

            var organisationNamePreference = preferences.FirstOrDefault(p => p.Name == "Organisation Name");
            var organisationEmailPreference = preferences.FirstOrDefault(p => p.Name == "Organisation Email");
            var organisationPhonePreference = preferences.FirstOrDefault(p => p.Name == "Organisation Phone");
            var organisationStreetAddressPreference = preferences.FirstOrDefault(p => p.Name == "Organisation Street Address");
            var organisationPostalCodePreference = preferences.FirstOrDefault(p => p.Name == "Organisation Postal Code");
            var organisationLocalityPreference = preferences.FirstOrDefault(p => p.Name == "Organisation Locality");

            model.OrganisationName = organisationNamePreference == null
                ? string.Empty
                : organisationNamePreference.Value;

            model.OrganisationEmail = organisationEmailPreference == null
                ? string.Empty
                : organisationEmailPreference.Value.Replace("@", "//").Replace(".", "/");

            model.OrganisationPhone = organisationPhonePreference == null
                ? string.Empty
                : organisationPhonePreference.Value;

            model.OrganisationStreetAddress = organisationStreetAddressPreference == null
                ? string.Empty
                : organisationStreetAddressPreference.Value;

            model.OrganisationPostalCode = organisationPostalCodePreference == null
                ? string.Empty
                : organisationPostalCodePreference.Value;

            model.OrganisationLocality = organisationLocalityPreference == null
                ? string.Empty
                : organisationLocalityPreference.Value;

            return PartialView("Partials/Footer", model);
        }

    }
}

Ottostugan/Views/Shared/_Layout.cshtml
@using Ottostugan.Resources
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@Page.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    @UI.Head()
    <script type="text/javascript" src="~/Scripts/head.js"></script>
    <link type="text/css" rel="stylesheet" href="~/Content/Css/screen.css?v=2023-05-133343331114211" media="screen" />
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:400,400italic,700,700italic" media="screen">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Sorts+Mill+Goudy:400,400italic" media="screen">
    <link rel="stylesheet" type="text/css" href="~/Content/Css/print.css" media="print">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.1.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("head", required: false)
</head>
<body class="p-1 m-0 border-0 bd-example m-0 border-0">
    @Html.Hidden("__page__culture__", @System.Globalization.CultureInfo.CurrentUICulture.Name)
    <div id="root" class="container">
        <header id="top" class="mb-4">
            <h1 class="text-center">
                <a href="/" accesskey="h" class="main-logo" title="@Ottostugan.Resources.Labels.Ottostugan"></a>
            </h1>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                        @*<a class="navbar-brand" href="#">Hidden brand</a>*@
                        <ul class="navbar-nav mx-auto  d-flex justify-content-center align-items-center">
                            <li class="nav-item">
                                <a class="nav-link active" accesskey="1" href="/">Vinter i Grönklitt </a>
                                @*<a class="nav-link active" aria-current="page" href="#">Home</a>*@
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" accesskey="2" href="/summer">Sommar i Grönklitt</a>
                                @*<a class="nav-link" href="#">Link</a>*@
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" accesskey="3" href="/apartments">Lägenheter</a>
                                @*<a class="nav-link" href="#">Link</a>*@
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" accesskey="4" href="/about-us">Om oss</a>
                                @*<a class="nav-link" href="#">Link</a>*@
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" accesskey="5" href="/contact-us">Kontakta oss</a>
                                @*<a class="nav-link" href="#">Link</a>*@
                            </li>
                            @*@UI.Menu(StopLevel: 1, CssClass: "navbar-nav me-auto mb-2 mb-lg-0")*@
                        </ul>
                    </div>
                </div>
            </nav>
            @*<nav id="skip" class="d-flex justify-content-center">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" accesskey="n" href="#nav">@Ottostugan.Resources.Labels.SkipToNavigation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" accesskey="c" href="#content">@Ottostugan.Resources.Labels.SkipToContent</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" accesskey="f" href="#footer">@Ottostugan.Resources.Labels.SkipToFooter</a>
                </li>
            </ul>
        </nav>
        <nav id="nav" class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                @UI.Menu(StopLevel: 1, CssClass: string.Empty)
            </div>
        </nav>*@
        </header>
        @RenderBody()
        <footer id="footer" class="footer bg-light text-center py-3">
            @Html.Action("Footer", "Main")
        </footer>
    </div>
    <script type="text/javascript">
        head.js('http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js',
            'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js',
            '@Url.Content("/Scripts/jquery.validate.min.js")',
            '@Url.Content(Ottostugan.Helpers.GlobalizeUrls.Globalize)',
            '@Url.Content(Ottostugan.Helpers.GlobalizeUrls.GlobalizeCulture)',
                '@Url.Content("/Scripts/jquery.validate.unobtrusive.min.js")',
                '@Url.Content("/Scripts/jquery.unobtrusive-ajax.min.js")',
                '@Url.Content("/Scripts/globalize/globalize.validation.js")',
                '@Url.Content("/Scripts/scripts.js")')

        window.monthNames = [
            '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.January))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.February))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.March))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.April))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.May))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.June))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.July))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.August))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.September))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.October))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.November))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.December))'];

            window.dayNames = [
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.Sunday))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.Monday))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.Tuesday))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.Wednesday))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.Thursday))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.Friday))',
                '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.Saturday))'];

            window.weekNumberLabel = '@Html.Raw(HttpUtility.JavaScriptStringEncode(Labels.Week))';

    </script>
</body>
@RenderSection("script", required: false)
</html>